/* Generated by xtask! Don't MODIFY IT! */
pub const _CONFIG_KERNEL_BASE: usize = 0xffffffff00000000;
pub const _CONFIG_PAGE_SHIFT: usize = 12;
pub const _CONFIG_NR_CPUS: usize = 8;
pub const _CONFIG_STACK_SIZE: usize = 8192;
pub const _CONFIG_BOOT_HEAP_SIZE: usize = 0x20000;
pub const _CONFIG_KERNEL_ASPACE_BASE: usize = 0xffff_0000_0000_0000;
pub const _CONFIG_ARCH_PHYSMAP_SIZE: usize = 1 << 39;
pub const _CONFIG_MMU_MAX_LEVEL: usize = 5;
